import ItemCard from '../../Reusable/ItemCard'
import Button from '@material-ui/core/Button'
import Dialog from '@material-ui/core/Dialog'
// import Divider from '@material-ui/core/Divider'
import AppBar from '@material-ui/core/AppBar'
import Toolbar from '@material-ui/core/Toolbar'
import Slide from '@material-ui/core/Slide'
import CloseIcon from '@material-ui/icons/Close'
import IconButton from '@material-ui/core/IconButton'
// import ListItemText from '@material-ui/core/ListItemText'
// import ListItem from '@material-ui/core/ListItem'
// import List from '@material-ui/core/List'
import FormControl from '@material-ui/core/FormControl'
import FormGroup from '@material-ui/core/FormGroup'
import TextField from '@material-ui/core/TextField'
import FormHelperText from '@material-ui/core/FormHelperText'
// import InputLabel from '@material-ui/core/InputLabel'
// import 'typeface-roboto'
import gql from 'graphql-tag'
import { Query, ApolloConsumer } from 'react-apollo'
