apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: 794213689372.dkr.ecr.ap-south-1.amazonaws.com/admin-frontend:1.0.0

          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SERVER_HTTP_URI
              value: "https://api.school.aquilatrack.com/"
            - name: REACT_APP_SERVER_WS_URI
              value: "wss://api.school.aquilatrack.com/"
            - name: PORT
              value: "8080"
          imagePullPolicy: Always
